databases:
  - name: customcodestudio
    databaseName: customcodestudio
    user: codeuser
    ipAllowList: []
    plan: free

services:
  - type: web
    name: customcodestudio
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: customcodestudio
          property: connectionString

  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
